#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define DIMS 4;

TSemaphore semaphore;
bool actuar[DIMS];

void iniciar_actuar(){
	for(i = 0; i < DIMS; i++){
		actuar[i] = true;
	}
}

void actualizar_actuar(int x){
	for(i = 0; i < DIMS; i++){
		if (i != x)
			actuar[i] = false;
	}
}

void recto(){
	setMotorSpeed(motorB, 30);
	setMotorSpeed(motorC, 30);
}

void atras(){
	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, -30);
}

void parar(){
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}

void giro_drch(){
	setMotorSpeed(motorB, 30);
	setMotorSpeed(motorC, -30);
}

void giro_izq(){
	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, 30);
}

task task_luz{
	while (true){
		semaphoreLock(semaphore);
		if (bDoesTaskOwnSemaphore(semaphore)){
			if(actuar[2]){
				actualizar_actuar(4);
				semaphoreUnlock(semaphore);
				recto();
			}

		}
		abortTimeslice();
	}
}

task task_recto{
	while (true){
		semaphoreLock(semaphore);
		if (bDoesTaskOwnSemaphore(semaphore)){
			if(actuar[4]){
				actualizar_actuar(4);
				semaphoreUnlock(semaphore);
				recto();
			}
		}
		abortTimeslice();
	}
}

task main()
{
	semaphoreInitialize(semaphore);
	iniciar_actuar();

	startTask(task_recto);
	startTask(task_luz);

	while (true){
		abortTimeslice();
	}
}
